DROP DATABASE IF EXISTS stree ;
CREATE DATABASE stree;
USE stree;

CREATE TABLE MEMBER (
	ID INT NOT NULL,
	Name TEXT NULL,
	Account VARCHAR(50) NOT NULL,
    Password TEXT NOT NULL,
	Email TEXT NOT NULL,
	Address TEXT NULL,
	Phone_Number TEXT NULL,
	Birthday DATE NULL,
	PRIMARY KEY (ID),
	UNIQUE (Account)
);

CREATE TABLE GAME (
	ID INT NOT NULL,
    Name TEXT NOT NULL,
    Price INT NOT NULL,
    ClickCount INT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TRACE (
	CustomerID INT NOT NULL,
    GameID INT NOT NULL,
    Date_Time DATE NOT NULL,
    PRIMARY KEY (CustomerID,GameID),
    FOREIGN KEY (CustomerID) REFERENCES MEMBER(ID),
    FOREIGN KEY (GameID) REFERENCES GAME(ID)
);

CREATE TABLE COMMENT (
	CustomerID INT NOT NULL,
    GameID INT NOT NULL,
    Date_Time DATE NOT NULL,
    Score INT NOT NULL,
    Impression TEXT NULL,
    PRIMARY KEY (CustomerID,GameID),
    FOREIGN KEY (CustomerID) REFERENCES MEMBER(ID),
    FOREIGN KEY (GameID) REFERENCES GAME(ID)
);

CREATE TABLE SHOPPING_CAR (
	CustomerID INT NOT NULL,
    GameID INT NOT NULL,
    Date_Time DATE NOT NULL,
    Game_Quantity INT NOT NULL,
    PRIMARY KEY (CustomerID,GameID),
    FOREIGN KEY (CustomerID) REFERENCES MEMBER(ID),
    FOREIGN KEY (GameID) REFERENCES GAME(ID)
);

CREATE TABLE HISTORY (
	CustomerID INT NOT NULL,
    GameID INT NOT NULL,
    Date_Time DATE NOT NULL,
    PRIMARY KEY (CustomerID,GameID),
    FOREIGN KEY (CustomerID) REFERENCES MEMBER(ID),
    FOREIGN KEY (GameID) REFERENCES GAME(ID)
);

CREATE TABLE DEVELOPER (
	ID INT NOT NULL,
    Name TEXT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TAG (
	ID INT NOT NULL,
    Add_Time DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TAG_ADD (
	GameID INT NOT NULL,
	TagID INT NOT NULL,
    PRIMARY KEY (TagID,GameID),
    FOREIGN KEY (TagID) REFERENCES TAG(ID),
    FOREIGN KEY (GameID) REFERENCES GAME(ID)
);

CREATE TABLE ORDER_LIST (
	ID INT NOT NULL,
    Date_Time DATE NOT NULL,
    Total INT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ORDER_ITEM (
	OrderID INT NOT NULL,
    GameID INT NOT NULL,
    Quantity INT NOT NULL,
    Price INT NOT NULL,
    PRIMARY KEY (OrderID,GameID),
    FOREIGN KEY (OrderID) REFERENCES MEMBER(ID),
    FOREIGN KEY (GameID) REFERENCES GAME(ID)
);

CREATE TABLE GAME_LIST (
	ID INT NOT NULL,
    Date_Time DATE NOT NULL,
    Profit INT NULL,
    Sell_Quantity INT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GAME_LIST_ADD (
	GameID INT NOT NULL,
	GAME_LIST_ID INT NOT NULL,
    PRIMARY KEY (GAME_LIST_ID,GameID),
    FOREIGN KEY (GAME_LIST_ID) REFERENCES GAME_LIST(ID),
    FOREIGN KEY (GameID) REFERENCES GAME(ID)
);

SHOW TABLES;